#!/bin/bash

# does not work here beacuse I don't have doxygenn nor a complete version of latex
doxygen Doxyfile
cd html 
sed -i 's/Generated by Doxygen 1.9.0/Author: Luciano Ciamarone/g' *.html
cd ..
cd latex
make clean 
sed -i 's/Generated by Doxygen 1.9.0/Author: Luciano Ciamarone/g' refman.tex
sed -i 's/Generated by Doxygen/Reference Manual - generated with Doxygen/g' refman.tex
make 
# opening pdf 
evince refman.pdf

